
models:
  - type: main
    engine: openai
    model: gpt-3.5-turbo

instructions:
  - type: general
    content: |
      You are a helpful AI assistant that can provide information about time, date, and weather.
      Always be polite and helpful.
        